---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: atomicBlue-Desktop
description: My Wayblue Hyprland (NVIDIA Open) image

base-image: ghcr.io/wayblueorg/hyprland-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - micro

  - type: systemd
    system:
      enabled:
        - bluetooth.service
        - tailscaled.service

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        install:
            - com.github.tchx84.Flatseal
            - io.github.flattool.Warehouse
            - org.kde.okular
            - org.kde.kate
            - org.libreoffice.LibreOffice
            - com.github.jeromerobert.pdfarranger
            - md.obsidian.Obsidian

      - scope: user
        notify: true
        install:
            - app.zen_browser.zen
            - com.discordapp.Discord
            - com.valvesoftware.Steam
            - md.obsidian.Obsidian

  - type: signing
